### ISSUE TITLE
curved arrow lines do not follow zoom

### ISSUE THREAD

**Issue by WarWolfen** [karellodewijk/wottactics#11]
Found the following issue:
If I paint a curved arrow, the arrow does not apply the zoom level, if I zoom out or in afterwards. It keeps its absolute size.

**Comment by karellodewijk** [comment]
It's not really a bug, it's intentional. 

I did experiment a bit with auto scaling things other than icons but it felt a little weird. You can try for yourself by adding &adjust_zoom to the url. 

There's also a short post about it here: http://forum.gametactic.org/forums/topic/on-the-subject-of-auto-scaling/

**Comment by WarWolfen** [comment]
Oh, I think this is a misunderstanding then... I do not mind the icons to scale... but if you draw an arrow to indicate a movement a unit should make from point a to point b on the map... this arrow needs to scale with the map (when applying the mousewheel), because otherwise the starting- and endpoint of the movement is completly wrong.

This does not happen with rectangles or other forms, just for the curved arrows (as far as I have experienced) and in case this is intentional (I might have got it wrong!), it is very weird. Because if it is, the arrow is only accurate in the zoomlevel it was drawn and is rendered useless as soon as a zoom is applied. Not sure if I was clear on this...
:/

**Comment by WarWolfen** [comment]
Picture one:
![image](https://user-images.githubusercontent.com/16292643/29779126-e623937c-8c11-11e7-9411-cec328ab87f3.png)

**Comment by WarWolfen** [comment]
Picture 2 (zoomed a bit):
![image](https://user-images.githubusercontent.com/16292643/29779159-03b4f49e-8c12-11e7-9233-b16866a3ad7b.png)

**Comment by WarWolfen** [comment]
See where I am coming from? The arrow does point from completly different starting point to a completly different ending point depending on the zoom. That can't be correct...

**Comment by karellodewijk** [comment]
Yes I see that definitely is not supposed to happen.

Can I ask what browser are you using ?
Did you complete the arrow before zooming (click in the circle again) ?

**Comment by WarWolfen** [comment]
I used Chrome (latest) to reproduce this issue. When I started zooming, I kind of "felt" I had completed the arrow (by right-clicking). I was able to use the mouse without dragging the arrow anywhere, so I assume the arrow was "completed".

EDIT:
But that might very well be the issue here. Probably I did not correctly "complete" it (?). This could be maybe enhanced by changing the cursor icon during the time the line has not been completed to indicate the status...

**Comment by karellodewijk** [comment]
I think I get it now.

Right clicking was never really supposed to complete the arrow, although it
does make sort of sense. And if you do right click, the arrow locks in
place and sort of bugs out.

I think I'll just make right click complete the arrow, it's probably more
intuitive anyway.

Anyway for now to complete an arrow double click, or click in the last
circle.

Thanks for reporting this, and sorry I misunderstood.

**Comment by WarWolfen** [comment]
Thank you for clarification! Now I know how I can use it!
:)

**Comment by karellodewijk** [comment]
I changed right click to cancel whatever you were doing. I probably should look into making panning and drawing work well together. Anyway, this should avoid the confusion for now.
