### ISSUE TITLE
Issue: Cannot access/view map tactics

### ISSUE THREAD

**Issue by lsnellman** [karellodewijk/wottactics#15]
Not sure this should be posted here..

Currently you cannot edit/view any map tactics. This issue popped up 12/19, probably something not related to the code broke. image of the problem -> https://imgur.com/a/B2O39

I would theorize it has something to do with the login process since you cannot log in currently, unless you were previously. 

How to reproduce -> create a new map room and attempt to do anything.

**Comment by lsnellman** [comment]
Also prevents people from logging in to post the issue on the forums :)

**Comment by karellodewijk** [comment]
Sorry about the issues, they should be fixed now. 

You were spot on about it being a login issues. The redis service which stores user sessions became unresponsive and all other problems stem from there.
