### ISSUE TITLE
Maintainer

### ISSUE THREAD

**Issue by NikoGrano** [karellodewijk/wottactics#32]
Hey.

Due lack of maintaining. I would like step forward and take responsibility about maintaining this project and it's related servers.

Ping @karellodewijk

**Comment by HellaCopteRescue** [comment]
I agree with Niko He has been a solid contributor.

**Comment by NikoGrano** [comment]
Lifting server resources from 2 cores to 10 cores.
Also adding RAM from 4GB to 24 GB.

**Comment by NikoGrano** [comment]
Resources has been lowered right after the event ended. However, we have started new project to create replacement for this service. I will be shutting down sponsored servers, when replacement is ready.

Servers are currently sponsored by https://secure.ironlions.fi and new replacement is beign worked at https://github.com/GameTactic. For more information, check https://gametactic.eu or join Discord https://discord.gg/N4EQ9CW.
