### ISSUE TITLE
Change Port

### ISSUE THREAD

**Issue by NikoGrano** [karellodewijk/wottactics#4]
How I do change port from 80 to something else. I will be using nginx for reverse proxy.

**Comment by karellodewijk** [comment]
You need to copy secrets.txt.template to secrets.txt and then edit the port value in that file.

**Comment by karellodewijk** [comment]
Also see https://github.com/karellodewijk/wottactics/issues/3 for working nginx options.

**Comment by NikoGrano** [comment]
Thanks. I'm now Officially blind!
