### ISSUE TITLE
Login issues

### ISSUE THREAD

**Issue by Cinphul** [karellodewijk/wottactics#7]
When I click on the NA server to log in, WoTTactic.com spins and spins then crashes to empty page.  When I click on RU or ASIA to test, I successfully get re-directed to the those server (but obviously can't log in / validate).

I've cleared my cache, tried multiple browsers, disabled my AV and Firewall and still can't validate.  Any thoughts / suggestions?

User name Cinphul

**Comment by NikoGrano** [comment]
@Cinphul Seems like NA servers are super-slow (At least when looking from EU). It might be problem with Wargaming. Also It seems EU site is also very slow.

Please wait for while. We will see. I will try investigate this, but only @karellodewijk can see the logs.

**Comment by NikoGrano** [comment]
@Cinphul @karellodewijk 

Login via NA is confirmed to be working. Please note, all wargaming sites are right now very slow. It might be something with their servers or it might be DDoS.

~~*_This issue is not related to Wottactic, this issue is related to Wargaming servers right now._*~~

**Comment by Cinphul** [comment]
I'm trying again but this has been going on for about 2 days for me

**Comment by NikoGrano** [comment]
@Cinphul 

Roger. I just looked into it and it was working for me. Maybe @karellodewijk can find something from the logs.... Thanks for reporting this issue!

**Comment by Cinphul** [comment]
Also tried from a different computer, same issue

**Comment by NikoGrano** [comment]
So, to really investigate this issue I decided to start a clean Linux Mint VM. And Yes, I did find following problems. (And WG servers are not anymore so f super-slow...)

----------------

@karellodewijk Issue is confirmed.

Steps done.
1. Click to login. (ok)
2. After login is successful and redirect view is showed to user, callback get's stuck with url `https://na.wargaming.net/id/sso/signin/notify/next=/id/openid/{CENSORED}/&trust_root=http%3A%2F%2Fwottactic.com%2Fauth%2Fopenid%2Fcallback` 
(User sees following view: `https://api.worldoftanks.eu/wot//blank/`)
3. After waiting few mins (aka, one wot round.) Wottactic returned `ERR_EMPTY_RESPONSE` with url `http://wottactic.com/auth/openid/undefined`. 

I expect you will find more details from log files.


-----------------

@Cinphul So, issue is confirmed, thank you for reporting it here! @karellodewijk will fix it. If you want see possible progress, you will see it here.

**Comment by karellodewijk** [comment]
I found the issue, the website would sometimes issue a cookie for a language subdomain rather than a domain cookie. After login it would redirect you to the main domain and would no longer have access to the cookie and your session causing login to fail.

I think I fixed it, can you confirm ?

**Comment by Cinphul** [comment]
I'll try as soon as I'm at my computer, should be about 5 hours from now.  Thank you.

**Comment by NikoGrano** [comment]
@karellodewijk, confirmed to be working with my mobile browser. (Never visited wottactic.com via mobile :D)

Great job Kalith, like always. ;)

**Comment by Cinphul** [comment]
Sorry for delay, just wanted to confirm it worked and I'm in.  Thank you.

**Comment by karellodewijk** [comment]
Ok, sorry for breaking things and thank you for the help.
